services:
  http-api-cpp:
    image: toncenter/ton-http-api-cpp:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: --config /app/static_config.yaml
    ports:
      - ${SERVER_PORT:-8081}:8081
      - ${MONITOR_PORT:-8082}:8082
    restart: unless-stopped
    secrets:
      - ton-global-config
      - config-vars
    ulimits:
      memlock: 4194304
secrets:
  ton-global-config:
    file: ${TON_BLOCKCHAIN_CONFIG_PATH:-private/private-config.json}
  config-vars:
    file: ${TON_SERVICE_CONFIG_PATH:-private/config-vars.yaml}
