services:
  http-api-cpp:
    image: toncenter/ton-http-api-cpp:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: --config /app/static_config.yaml --config_vars /run/secrets/config-vars
    ports:
      - ${THACPP_PORT:-8081}:8081
      - ${THACPP_MONITOR_PORT:-8082}:8082
    restart: unless-stopped
    secrets:
      - ton-global-config
      - config-vars
    ulimits:
      memlock: -1
secrets:
  ton-global-config:
    file: ${THACPP_GLOBAL_CONFIG_PATH:-private/mainnet.json}
  config-vars:
    file: ${THACPP_CONFIG_VARS:-private/config_vars.yaml}
