components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 16
    fs-task-processor:
      worker_threads: 2
    monitor-task-processor:
      thread_name: monitor_thread
      worker_threads: 1
  default_task_processor: main-task-processor
  components:
    server:
      listener:
        port: 8877
        connection:
          in_buffer_size: 1048576
          requests_queue_size_threshold: 1024
        task_processor: main-task-processor
      listener-monitor:
        port: 8878
        task_processor: monitor-task-processor
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: "@null"
          level: warning
          format: json
          overflow_behavior: discard
        api-v2:
          file_path: "@stdout"
          level: info
          format: json
          overflow_behavior: discard
    tonlib:
      global_config: ./private/global-config.json
      keystore: /tmp/keystore/
      threads: 16
      task_processor: main-task-processor
    handler-server-monitor:
      path: /stats
      method: GET
      task_processor: main-task-processor
      format: json
    handler-ping:
      path: /health
      method: GET
      task_processor: main-task-processor
      log-level: warning
    handler-api-v2:
      path: /api/v2/{ton_api_method}
      method: GET,POST
      task_processor: main-task-processor
